### ISSUE TITLE
All functions return undefined and doesn't set value

### ISSUE THREAD

**Issue by mauricioklein** [faeldt/redis-mock#59]
I'm trying to use `redis-mock` but no call is being accepted. All of them returns undefined and the callback isn't called.

```js
const mock = require("redis-mock")
const client = mock.createClient()

client.SET("x", "5", ()=>{})
// undefined

client.GET("x", (err, val) => console.log(err, val))
// undefined, and nothing is printed
```

This happens to all redis supported functions.

Any hint about what the problem could be?

Thanks!

**Comment by Kylar13** [comment]
Why are you using SET() and not set()?? 

Node client uses lowercase, and this is a mock of said client. Could that be the issue?

**Comment by lub0v** [comment]
@mauricioklein I'm also facing this issue, do you remember what was the problem?

**Comment by oreporan** [comment]
everything is undefined for me also:

```ts
     import redis from 'redis-mock';
     jest.mock('redis', () => redis);

      it('gets the state', async () => {
           const redisClient = redis.createClient()
            const mockedRenderId = 'renderId';
            await redisClient.set(`${mockedRenderId}_state`, 'rendering');
            const x = await redisClient.get(`${mockedRenderId}_state`)
            console.log('beep', x); // undefined
        });
```

**Comment by rjdmacedo** [comment]
> everything is undefined for me also:
> 
> ```ts
>      import redis from 'redis-mock';
>      jest.mock('redis', () => redis);
> 
>       it('gets the state', async () => {
>            const redisClient = redis.createClient()
>             const mockedRenderId = 'renderId';
>             await redisClient.set(`${mockedRenderId}_state`, 'rendering');
>             const x = await redisClient.get(`${mockedRenderId}_state`)
>             console.log('beep', x); // undefined
>         });
> ```

☝🏼 for me as well. Any clue on what might cause this issue?

**Comment by SagnikPradhan** [comment]
This has been open since 2018 and no reply from contributors?

**Comment by mirkosoft** [comment]
For me it does work but I don't use arrow functions as callbacks. For example:
```
client.hgetall("myHash", function(err, result) { console.log(result) })
> { test: '[object Object]', test2: '[object Object]' }
```
instead of:
```
client.hgetall("myHash", (result, err) => console.log(result))
> null
```

**Comment by rahul-ghimire-au6** [comment]
@mauricioklein is this issue resolved ???  because still it is giving undefined for me also.
```
client.SET("x", "5", ()=>{})
// undefined

client.GET("x", (err, val) => console.log(err, val))
// undefined, and nothing is printed
```

**Comment by josephzakzuk** [comment]
I did it this way and it worked (Because redis-mock functions require a callback to work):   

 ```
await client.set('simpleKey', 'simpleValue');

 const simpleValue = await new Promise((resolve, reject) => {
      client.get('simpleKey', (err, result) => {
        if (err) {
          reject(err);
        } else {
          console.log('::::: B :::::');
          resolve(result);
        }
      });
    });

console.log(simpleValue);
```
