### ISSUE TITLE
hgetall callback has empty object as reply when called with a non-existent key

### ISSUE THREAD

**Issue by snapfractalpop** [faeldt/redis-mock#8]
The hgetall function should have a null reply object when called with a non-existent key. This is the case in the real version of the redis module (by mranney). In this mock version, the reply is {} for non-existent keys, which is "truthy". As a result, this breaks some tests.

**Comment by DanielTaika** [comment]
Did this issue arise from the dead? I see {} when expecting null
[Redis 7.x, NodeJS 16, Linux]

**Comment by kerimembel** [comment]
I was able check if it is null or not like this;

`redisClient.hGetAll('orders').then((data) => {

    if(Object.keys(data).length) {
      console.log("Not empty");
    } else {
      console.log("empty");
    }
  })`
